# Generated by Django 4.1.5 on 2023-01-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_contatoajuda_usuario_delete_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatoajuda',
            name='nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='contatoajuda',
            unique_together={('usuario', 'email')},
        ),
    ]
